
Vagrant.configure("2") do |config|

  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
    v.vmx["guestOS"] = "ubuntu-64"
    v.vmx["memsize"] = "2048"
  end  

  config.vm.define "ubuntu1" do |ubuntu1|
    ubuntu1.vm.box = "generic/ubuntu2004"
    ubuntu1.vm.network "private_network", ip: "192.168.100.5"
    ubuntu1.vm.hostname = "ubuntu1"
  end
  config.vm.define "ubuntu2" do |ubuntu2|
    ubuntu2.vm.box = "generic/ubuntu2004"
    ubuntu2.vm.network "private_network", ip: "192.168.100.6"
    ubuntu2.vm.hostname = "ubuntu2"
  end
  config.vm.define "ubuntu3" do |ubuntu3|
    ubuntu3.vm.box = "generic/ubuntu2004"
    ubuntu3.vm.network "private_network", ip: "192.168.100.7"
    ubuntu3.vm.hostname = "ubuntu3"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y
    echo "Hello world ${hostname}"
    SHELL
  
end
